### ISSUE TITLE
[Bug]: Some of "File Menu" can't be displayed.

### ISSUE THREAD

**Issue by Immortal-Sty** [phibr0/obsidian-commander#32]
### Describe the bug

The following error occurs when I right-click a file, but it works again when I click "more options".

### Steps to reproduce

1. Download the plugins named "AidenLx's Folder Note" and "Folder Note Core";
2. Add the "Folder Note Core: Delete linked folder" and "Folder Note Core: Make current document folder note" to the "File Menu";
3. Right-click a file;
4. Click "more options".

### Expected Behavior

The "File Menu" can't work, when you right-click a file.

But it displays one of these two commands when I click "more options".

### Operating system

Windows

**Comment by phibr0** [comment]
Some Commands are so called "checked" commands. This means, the Plugin that initially added the Command to obsidian determines if the command can run in the current situation (for example because it depends on an active editor), and if it can't it won't be displayed. I think this is an issue with the plugin itself deciding that these commands cannot be run, and thus commander won't display them
