### ISSUE TITLE
Change menu presentation so that scrolling is not required

### ISSUE THREAD

**Issue by Triquetra** [phibr0/obsidian-commander#8]
### Describe the feature

currently, the top navigation menu for the app scrolls out of visible range, creating a scrollbar that is necessary to interact with the remaining menu items.

### Does this fix a problem? If so, specify.

It is a minor annoyance be required to scroll to the Page Header menu item, especially since that is the one I use most.

### Screenshots and recordings

![2022-07-26 10_42_33-2022-W31 - David - Obsidian v0 15 8](https://user-images.githubusercontent.com/195027/181075676-106ea412-8bd7-46d5-ab6a-015ff9fc3f47.png)

**Comment by phibr0** [comment]
The Plugin was developed with the default theme in mind, in which the Settings Modal is wide enough to fit all tabs. As a workaround, you can also use <kbd>Tab</kbd> and <kbd>Shift</kbd> + <kbd>Tab</kbd> to navigate the Settings.

**Comment by jsmorabito** [comment]
> ### Describe the feature
> currently, the top navigation menu for the app scrolls out of visible range, creating a scrollbar that is necessary to interact with the remaining menu items.
> 
> ### Does this fix a problem? If so, specify.
> It is a minor annoyance be required to scroll to the Page Header menu item, especially since that is the one I use most.
> 
> ### Did you consider other alternatives?
> _No response_
> 
> ### Screenshots and recordings
> ![2022-07-26 10_42_33-2022-W31 - David - Obsidian v0 15 8](https://user-images.githubusercontent.com/195027/181075676-106ea412-8bd7-46d5-ab6a-015ff9fc3f47.png)

hey @Triquetra thanks for the feedback! We're actually going to look into a solution for this problem. Tentatively, the plan is to rearrange the menu item order so that the more frequently used menu items (based on our educated guess) will appear sooner in the list. The page header menu tab will be closer to the front of the list and will be more convenient to access. A reimagining of the settings menu or an alternative solution to bypass this issue will take more consideration, but hopefully the quick fix outlined will work for you for now. thanks again and let us know if you encounter any more issues or have any more ideas for how we can improve the plugin!

**Comment by Triquetra** [comment]
I'm using the Minimal theme, and I didn't even consider that my theme could be the problem as suggested by @phibr0. It's certainly reasonable that UI development target only the default theme, but I don't want to give up Minimal, so I figured I'd just live with it. Thank you, @jsmorabito! Your proposed solution would certainly help me, hopefully without inconveniencing others.

**Comment by Triquetra** [comment]
In the spirit of your proposed solution, @jsmorabito, I'd suggest moving the "General" tab to last place, since once its options are set according to the user's wishes, it will not likely be accessed again.
